default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: greenland_dev
test:
  <<: *default
  database: greenland_test
production:
  <<: *default
  database: greenland_production
  username: greenland
  password: <%= ENV["GREENLAND_DATABASE_PASSWORD"] %>

